[project]
name = "25-mlops"
version = "0.1.0"
description = "uv files for MLOps zoomcamp :-)"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "marimo>=0.13.10",
    "matplotlib>=3.10.3",
    "numpy>=2.2.6",
    "pandas>=2.2.3",
    "pyarrow>=20.0.0",
]
